CREATE TABLE "tb_body_measurements" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL REFERENCES "tb_users"("id"),
  "weight_kg" decimal(5,2) NOT NULL,
  "height_cm" decimal(5,2) NOT NULL,
  "chest_cm" decimal(5,2),
  "waist_cm" decimal(5,2),
  "abdomen_cm" decimal(5,2),
  "hip_cm" decimal(5,2),
  "right_arm_cm" decimal(5,2),
  "left_arm_cm" decimal(5,2),
  "right_thigh_cm" decimal(5,2),
  "left_thigh_cm" decimal(5,2),
  "right_calf_cm" decimal(5,2),
  "left_calf_cm" decimal(5,2),
  "body_fat_percentage" decimal(5,2),
  "triceps_skinfold_mm" decimal(5,2),
  "subscapular_skinfold_mm" decimal(5,2),
  "chest_skinfold_mm" decimal(5,2),
  "axillary_skinfold_mm" decimal(5,2),
  "suprailiac_skinfold_mm" decimal(5,2),
  "abdominal_skinfold_mm" decimal(5,2),
  "thigh_skinfold_mm" decimal(5,2),
  "created_at" timestamp NOT NULL DEFAULT now(),
  "measured_by" uuid REFERENCES "tb_users"("id"),
  "notes" text
);